### ISSUE TITLE
SEB Failed to start a new session - Could not find Windows Runtime type 'Windows.Devices.WiFi.WiFiAccessStatus'

### ISSUE THREAD

**Issue by MoniaDi** [SafeExamBrowser/seb-win-refactoring#1069]
One of our students was unable to take the exam and encountered the error message: "SEB failed to start a new session" (SEB 3.6.0.633 on Windows 11). We attempted to enable the location services, but the issue persisted, even after upgrading to SEB 3.8.0.
ERROR: Caught unexpected exception while performing operation 'LazyInitializationOperation'!

   Exception Message: Access is denied
   Exception Type: System.ComponentModel.Win32Exception

   at SimpleWifi.Win32.WlanClient..ctor()
   at SimpleWifi.Wifi..ctor()
   at SafeExamBrowser.SystemComponents.Network.NetworkAdapter.Initialize() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\Network\NetworkAdapter.cs:line 92
   at SafeExamBrowser.Client.Operations.ShellOperation.InitializeSystemComponents() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 214
   at SafeExamBrowser.Client.Operations.ShellOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Client\Operations\ShellOperation.cs:line 81
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108
[2024-12-30_15h05m19s_Runtime.log](https://github.com/user-attachments/files/18282410/2024-12-30_15h05m19s_Runtime.log)
[2024-12-30_15h05m19s_Client.log](https://github.com/user-attachments/files/18282411/2024-12-30_15h05m19s_Client.log)

**Comment by dbuechel** [comment]
See #928, versions previous to 3.8.0 will not work on Windows 11 due to the system API / permission change.
