### ISSUE TITLE
SEB crashes after login with Azure AD multi factor authentication in Moodle

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#480]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/478

<div type='discussions-op-text'>

<sup>Originally posted by **AntonT76** October  4, 2022</sup>
Hello,

we installed the new version of SEB (3.4.0). We are using Moodle (3.9.*) with Open ID Connect authentication via Microsoft Azure AD and multi factor authentication. After pressing the login button in Moodle and Moodle will forward the user to the MF authentication site every times SEB will crash. Attached you can find a screenshot and SEB log files.

We changed a lot of SEB settings (eg: deactivate URL filtering, activate session handling) but it did not help.

Exception:
- login with older version SEB 3.2.0 works
- if MF authentication will be done before using SEB it will work (-> MF authentication in SEB isn't required)

How can we solve this problem?

thanks, br Anton
![SEB-error](https://user-images.githubusercontent.com/66412602/193740017-39fe6dae-8627-48e3-aa52-06f1b324faa1.png)
[2022-10-03_15h53m48s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/9702963/2022-10-03_15h53m48s_Browser.log)
[2022-10-03_15h53m48s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/9702964/2022-10-03_15h53m48s_Client.log)
[2022-10-03_15h53m48s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/9702965/2022-10-03_15h53m48s_Runtime.log)
</div>

### TODO

1. Add fix to JavaScript as mentioned in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/478#discussioncomment-3802496
2. Investigate possible frame access issue in error event handler, see https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/478#discussioncomment-3802490

**Comment by dbuechel** [comment]
Re ##2 above: Check if frame is valid before accessing it in `LoadError` event handler:

```
Exception Info: System.Exception
   at CefSharp.Internals.CefFrameWrapper.ThrowIfFrameInvalid()
   at CefSharp.Internals.CefFrameWrapper.get_IsMain()
   at SafeExamBrowser.Browser.BrowserControl.&lt;Initialize&gt;b__31_12(System.Object, CefSharp.LoadErrorEventArgs)
   at CefSharp.WinForms.ChromiumWebBrowser.CefSharp.Internals.IWebBrowserInternal.OnLoadError(CefSharp.LoadErrorEventArgs)
   at &lt;Module&gt;.CefSharp.Internals.ClientAdapter.OnLoadError(CefSharp.Internals.ClientAdapter*, scoped_refptr&lt;CefBrowser&gt;*, scoped_refptr&lt;CefFrame&gt;*, cef_errorcode_t, CefStringBase&lt;CefStringTraitsUTF16&gt;*, CefStringBase&lt;CefStringTraitsUTF16&gt;*)
```

**Comment by dbuechel** [comment]
See also #499.

**Comment by amaitland** [comment]
> as specified above: Check if frame is valid before accessing it in `LoadError` event handler:

Calling `IsMain` on an `IsValid == false` frame should actually be allowable, ThrowIFrameInvalid check will be removed in `M107`, commit https://github.com/cefsharp/CefSharp/commit/766ebbc8f6046c4100c5f88d4b1397647b556a14

**Comment by dbuechel** [comment]
Excellent, thanks a lot for the input. Then I'll definitely first update to the latest CefSharp version once I get around to having a look at the issue.

**Comment by AntonT76** [comment]
Dear @dbuechel 
thank you for this beta version. I did some tests with a user who needs multi factor authentication and the login will work fine. There is no crash of SEB.

br, Anton
