### ISSUE TITLE
0 Internal and 0 External Displays Detected

### ISSUE THREAD

**Issue by deetama** [SafeExamBrowser/seb-win-refactoring#599]
Hi, im using SEB 3.4.1.505, when i tried to open the app it says i have 0 internal and 0 external displays detected.

Its only happened for some pc (i have installed SEB for other pc but it seems fine, only a few have this problem).

Here is the log file for the error.
[2023-04-13_11h56m08s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11218315/2023-04-13_11h56m08s_Runtime.log)

Please help, and Thank you.

**Comment by dbuechel** [comment]
According to the log, you can't start SEB because SEB cannot get information about the connected displays:

```
2023-04-13 11:56:12.625 [08] - INFO: Validating display configuration...
2023-04-13 11:56:12.657 [08] - ERROR: [DisplayMonitor] Failed to query displays!

   Exception Message: Not supported 
   Exception Type: System.Management.ManagementException

   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at SafeExamBrowser.Monitoring.Display.DisplayMonitor.TryLoadDisplays(IList`1& displays) in C:\Users\appveyor\projects\seb-win-refactoring-4w22kouryjnrjj4t\SafeExamBrowser.Monitoring\Display\DisplayMonitor.cs:line 169

2023-04-13 11:56:12.657 [08] - WARNING: [DisplayMonitor] Failed to validate display configuration, active configuration is not allowed.
2023-04-13 11:56:12.657 [08] - ERROR: Display configuration is not allowed!
```

Could you please describe your hardware setup (PC + display(s))?

**Comment by dbuechel** [comment]
Are there any updates on this issue? Otherwise, we'd need to close it due to lack of feedback.

**Comment by jeroenhabets** [comment]
@deetama did you see @dbuechel follow up? Please respond asap or this request will be closed.

P.S. @ mentioning someone often makes people notice comments more easily.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
