### ISSUE TITLE
Facing an error while opening SEB after compiling it.

### ISSUE THREAD

**Issue by nxvvvv** [SafeExamBrowser/seb-win-refactoring#626]
I compiled SEB from the source code directly got from the repo and I'm getting this error:
`Method not found: 'Void SafeExam8rowser.Applications.ApplicationFactory..ctor(SafeExam8rowser.Monitoring.Contracts.Applications.lApplicationMonitor, SafeExam8rowser.Logging.Contracts.lModuleLogger,
SafeExamBrowser,WindowsApi.Contracts.lNativeMethods, SafeExamBrowser,WindowsApi.Contracts.lProcessFactory, SafeExamBrowser.SystemComponents.Contracts.Registry.lRegistnj)'.
at shutdown)
at SafeExam8rowser.Client.App.OnStartup(StartupEventArgs e)
at .ctor> _O(Object unused)
at System.Windows.Threading.ExceptionWrapper.lnternalRealCall(Delegate callback, Object args, Int32 numArgs)
at source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System. Windows.Threading.DispatcherOperation.lnvokelmp10
at MS.lnternal,CulturePreservingExecutionContext,CallbackWrapper(Object obj)
at System.Threading.ExecutionContext.Runlnternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System,Threading,ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at MS.lnternal,CulturePreservingExecutionContext,Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
at System.Windows.Threading.DispatcherOperation.lnvoke0
at System,Windows,Threading,Dispatcher,ProcessQueueO
at System.Windows.Threading.Dispatcher.WndProcHook(lntPtr hwnd, Int32 msg. IntPtr wParam, IntPtr IParam, Boolean& handled)
at MS.Win32.HwndWrapper,WndProc(lntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System,Windows,Threading,Dispatcher,Legacylnvokelmpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(lntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam)
at MS.Win32UnsafeNativeMethods,DispatchMessage(MSG& msg)
at System. Windows.Threading.Dispatcher.PushFramelmpl(DispatcherFrame frame)
at System,Windows,Application,RunDispatcher(Object ignore)
at System. Windows.Application.Runlnternal(Window window)
at SafeExamBrowser,Client.App.StartApplicationO
at SafeExam8rowser.Client.App.Main0`

Any possible ways to fix this?

**Comment by nxvvvv** [comment]
> 

I didn't notice the 8 and B. It wasn't intentional but yea I'll setup runtime application component as startup.

**Comment by nxvvvv** [comment]
I'm getting a warning `Integrity module not included!`. What's the cause and fix?

**Comment by nxvvvv** [comment]
Also while starting up its giving me this [ERROR](https://pastebin.mozilla.org/PKa9EbtK/raw). Please help me with that.

**Comment by dbuechel** [comment]
> I'm getting a warning Integrity module not included!. What's the cause and fix?

You can ignore that warning.

`2023-07-04 17:08:23.524 [08] - ERROR: Client instance terminated unexpectedly during initialization!`

You should find related information in the client log file and/or the exact reason of the crash in the Windows Event Viewer.

**Comment by nxvvvv** [comment]
Okay. Thank you.

**Comment by nxvvvv** [comment]
Basically there is no Client log created for this event and i tried running it a few more times but a client error isn't created here. What should i do?

**Comment by dbuechel** [comment]
There should be an error entry in the application log of the event viewer system utility of Windows. If there isn't any, it'd be pretty hard to diagnose what's going wrong from afar...

**Comment by nxvvvv** [comment]
Yea there is an error entry but it's not useful. It's just showing application terminated and there ain't any useful details there.

**Comment by dbuechel** [comment]
Are there any updates on this issue? Otherwise, we'd need to close it for the moment.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
