### ISSUE TITLE
ERROR: Caught unexpected exception while performing operation 'VirtualMachineOperation'

### ISSUE THREAD

**Issue by arielramos** [SafeExamBrowser/seb-win-refactoring#747]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
When I try to execute SEB in Windows 10, the app does not start correctly, older versions work fine, but latest 3.6.0 not.

**Steps to Reproduce**
1. Go to Moodle and start a new quiz attempt
2. The SEB will crash 

**Expected Behavior**
To start the quiz attempt with out any problems

**Screenshots**
<img width="1173" alt="Screenshot 2023-12-08 at 23 03 47" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/11698932/1a164dee-88b3-4c9c-82f4-60d846ff2e56">

**Version Information**
 - Windows 10 Professional
 - SEB-Version 3.6.0

**Additional Context**
```
2023-12-06 21:09:10.587 [09] - INFO: Validating virtual machine policy...
2023-12-06 21:09:10.603 [09] - ERROR: Caught unexpected exception while performing operation 'VirtualMachineOperation'!

   Exception Message: Object reference not set to an instance of an object.
   Exception Type: System.NullReferenceException

   at SafeExamBrowser.SystemComponents.VirtualMachineDetector.IsVirtualSystem(String biosInfo, String manufacturer, String model) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\VirtualMachineDetector.cs:line 116
   at SafeExamBrowser.SystemComponents.VirtualMachineDetector.HasHistoricVirtualMachineHardwareConfiguration() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\VirtualMachineDetector.cs:line 158
   at SafeExamBrowser.SystemComponents.VirtualMachineDetector.IsVirtualMachine() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\VirtualMachineDetector.cs:line 60
   at SafeExamBrowser.Runtime.Operations.VirtualMachineOperation.ValidatePolicy() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Runtime\Operations\VirtualMachineOperation.cs:line 54
   at SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:line 108

2023-12-06 21:09:10.606 [09] - INFO: ### -------------------------------------- Session Start Failed -------------------------------------- ###

2023-12-06 21:11:21.342 [09] - INFO: Initiating shutdown procedure...
2023-12-06 21:11:21.344 [09] - INFO: Stopping communication host...
```

**Comment by dbuechel** [comment]
@arielramos Could you please post the entire log files? Line 116 as specified above cannot cause a NullReferenceException (under normal circumstances, we have seen weird stack traces under not-normal circumstances like VMs...), see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/3.6.0/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L116.

@Notselwyn Do you see anything that could fail or lead to a NullReferenceException in the code checking for historic virtual machine configurations?

**Comment by Notselwyn** [comment]
A NullReferenceException should only be possible when `biosInfo`, `manufacturer`, and/or `model` is NULL I believe. The call is coming from https://github.com/SafeExamBrowser/seb-win-refactoring/blob/40d2b6acf07c0d610479d7287ce0754db10bd1df/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L158 

The `biosInfo` argument is defined as a format string, which means that it cannot be NULL. 

This means that probably the registry keys accessed here do not exist:

https://github.com/SafeExamBrowser/seb-win-refactoring/blob/40d2b6acf07c0d610479d7287ce0754db10bd1df/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L151-L152

Said registry keys are:

```
HKEY_LOCAL_MACHINE\SYSTEM\HardwareConfig\... -> SystemManufacturer
HKEY_LOCAL_MACHINE\SYSTEM\HardwareConfig\... -> SystemProductName
```

However, the return values are checked for function calls to `registry.TryRead()` on which the variables are depending. This leads to be believe there may be some malfunctioning of the return value of `registry.TryRead()` which is indicating the success of defining the output variable.

The return value indicating success only fails when an exception occurs. This gives me an idea: would it be possible that `Microsoft.Win32.Registry.GetValue()` does return NULL as value because the value name does not exist, yet does not trigger an exception. This is suggested by the docs @ https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registry.getvalue?view=net-8.0 . 

@dbuechel I suggest we implement this check:

```diff
		public bool TryRead(string key, string name, out object value)
		{
			var success = false;

			value = default;

			try
			{
				value = Microsoft.Win32.Registry.GetValue(key, name, default);
+				if (value != NULL)
					success = true;
			}
			catch (Exception e)
			{
				logger.Error($"Failed to read value '{name}' from registry key '{key}'!", e);
			}

			return success;
		}
```

**Comment by arielramos** [comment]
Hi, thank you for your reply, here you have the logs.
[2023-12-06_21h09m09s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13636737/2023-12-06_21h09m09s_Runtime.log)
[2023-12-08_22h30m51s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13636738/2023-12-08_22h30m51s_Client.log)

**Comment by dbuechel** [comment]
@Notselwyn Yes, I think you're right, that is actually a bug in the code which we should fix. The current implementation will indeed return true with an output value of `null` if the name and/or the key do not exist. Ideally, we should thus first check whether the key and name do in fact exist and only then attempt to read the value, but I could not find an API that would allow to do so. Are you aware of one?

If there's no API, then we'd actually need to make the check a bit more elaborate:

```diff
public bool TryRead(string key, string name, out object value)
{
+	var defaultValue = new object();

	value = default;

	try
	{
		value = Microsoft.Win32.Registry.GetValue(key, name, defaultValue);
	}
	catch (Exception e)
	{
		logger.Error($"Failed to read value '{name}' from registry key '{key}'!", e);
	}

+	return value != default && value != defaultValue;
}
```

I assumed that the actual value of a name can be `null` (e.g. for a binary or string value type) and hence did not `return value != default`, but scanning the actual framework implementation suggests otherwise: https://referencesource.microsoft.com/#mscorlib/microsoft/win32/registrykey.cs,c67ba10c47948465.

Would you agree that the above change in fact eliminates the bug and ensures that if we return `true`, then the output value will never be `null`? Or can there in fact be registry names with a value of `null`, which in turn would prevent us from checking for `value != default`?

**Comment by dbuechel** [comment]
@arielramos I still cannot explain your stack trace, that particular line of code cannot cause a `NullReferenceException` (it should, in case our analysis is correct, happen on line 119 or 120):

```
2023-12-06 21:09:10.603 [09] - ERROR: Caught unexpected exception while performing operation 'VirtualMachineOperation'!

   Exception Message: Object reference not set to an instance of an object.
   Exception Type: System.NullReferenceException

   at SafeExamBrowser.SystemComponents.VirtualMachineDetector.IsVirtualSystem(String biosInfo, String manufacturer, String model) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\VirtualMachineDetector.cs:line 116
   at SafeExamBrowser.SystemComponents.VirtualMachineDetector.HasHistoricVirtualMachineHardwareConfiguration() in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.SystemComponents\VirtualMachineDetector.cs:line 158
   [...]
```

Can you explain why there is no system information in the runtime log file resp. what computer are you using (manufacturer and model)?

```
# Computer 'WRR' is a                                   manufactured by                                 
```

**Comment by dbuechel** [comment]
Yes indeed, I think there is no way around actually trying out different approaches. I think `value != default` should work, as value is defined as an object reference and not a value type like e.g. int, but here again, I think the best would be to try it out and see what works (best). I shall take this up in our internal planning and tackle it next year.

**Comment by arielramos** [comment]
Hi, these are the computer specs:

Intel Core i7 2700K
Intel motherboard, DZ68BC LGA115 socket ATX form Z68 Express chipset
OCZ ZX Series 850W Fully-Modular 80PLUS Gold High Performance Power Supply
Antec DF-85 Black ATX Full Tower Computer Case
16GB (4 x 4GB) 240-Pin DDR3 SDRAM DDR3 1600 (PC3 12800)
Windows 7 Professional, upgraded to Windows 10 Professional
C:\ 1 TB SSD for programs 792 GB free
I:\ 1 TB SSD for data 480 GB free

Windows, BIOS, Norton updates all current.
Use Chrome updates current.
Also have Edge and Mozilla/FoxPro updates current

**Comment by arielramos** [comment]
Also I have these new log files:


[2023-12-12_20h37m33s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13656794/2023-12-12_20h37m33s_Runtime.log)

[2023-12-12_20h37m33s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13656793/2023-12-12_20h37m33s_Browser.log)

[2023-12-12_20h37m33s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13656792/2023-12-12_20h37m33s_Client.log)

**Comment by dbuechel** [comment]
> Hi, these are the computer specs:
> 
> Intel Core i7 2700K Intel motherboard, DZ68BC LGA115 socket ATX form Z68 Express chipset OCZ ZX Series 850W Fully-Modular 80PLUS Gold High Performance Power Supply Antec DF-85 Black ATX Full Tower Computer Case 16GB (4 x 4GB) 240-Pin DDR3 SDRAM DDR3 1600 (PC3 12800) Windows 7 Professional, upgraded to Windows 10 Professional C:\ 1 TB SSD for programs 792 GB free I:\ 1 TB SSD for data 480 GB free
> 
> Windows, BIOS, Norton updates all current. Use Chrome updates current. Also have Edge and Mozilla/FoxPro updates current

Thanks a lot. I presume you have a custom build which could explain the missing manufacturer and model name in the system info.

**Comment by dbuechel** [comment]
> Also I have these new log files:

As the client log file shows, you were running a prohibited application and SEB was unable to terminate it automatically:

```
2023-12-12 20:38:39.489 [01] - ERROR: Failed to automatically terminate application 'remoting_host.exe'!
```

**Comment by dbuechel** [comment]
Yes, we'll definitely improve the code as outlined above. You'd need to test the beta build once the changes are implemented in order to see whether these indeed fixed the issue, as the stack trace you posted still seems inexplicable to me. But that last line might just be an aftereffect of an earlier `NullReferenceException`, though that would be very big news to me (up and until today, every stack trace I've ever seen has been accurate).

**Comment by arielramos** [comment]
Hi, I have an apps called LogMeIn as a remote desktop, but, I closed the app in the task manager and then use the SEB, but issue persists.
[2023-12-13_10h59m30s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13668604/2023-12-13_10h59m30s_Runtime.log)
[2023-12-13_10h59m30s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13668605/2023-12-13_10h59m30s_Client.log)
[2023-12-13_10h59m30s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13668606/2023-12-13_10h59m30s_Browser.log)


I attach other logs.

**Comment by dbuechel** [comment]
Yes, that is still the same issue and I'm afraid you won't get around it until we implemented a fix (which is currently planned for January). If it is possible, try to downgrade and use SEB 3.5.0 in the meantime.

**Comment by dbuechel** [comment]
@arielramos Could you please test the latest beta build with the changes from @Notselwyn: https://sebdev-let.ethz.ch/api/buildjobs/c1928d85u6cyhqyn/artifacts/SEB_3.7.0.647_SetupBundle.exe.

**Comment by arielramos** [comment]
Hi @dbuechel , hope you are well, we downloaded the beta and now is working, thank you so much, we really appreciate your effords.

Regards

**Comment by dbuechel** [comment]
Excellent, thanks for testing and the timely feedback, much appreciated!
