### ISSUE TITLE
SEB - An expected error occured while trying to load configuration resource

### ISSUE THREAD

**Issue by nitapuji** [SafeExamBrowser/seb-win-refactoring#872]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
Hello, I have attached the screenshot of an error. it says "An expected error occured while trying to load configuration resource"...

**Expected Behavior**
It just happended one time. I did not have trouble with SEB before.

**Screenshots**
<img width="945" alt="image" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/122007800/b5618427-77d3-49dd-af48-551c409afd59">

**Version Information**
 - OS: Windows 11
 - SEB-Version: SEB_3.7.0.682
 
 Any help would be appreciated. Thank you

**Comment by dbuechel** [comment]
As mentioned in the error message, we'd need the log file of the affected session in order to determine what went wrong. If it only happened one time though, then it might likely have been a temporary network issue.

**Comment by ramsanegl** [comment]
I have the same issue..

When we try to load the configuration file, it is not able to load. When I downloded the file separately and then open, In the logs, it was giving TLS/SSL handshake error.

It suddenly stopped working. I have the logs.

@nitapuji If possible, please share the log files related to this.

And also, you can download the configuration file and try to open the seb by clicking on the file.. If it gives any error, pls share the log files for the same (runtime, client and browser).log

**Comment by ramsanegl** [comment]
/* Safe Exam Browser, Version 3.4.0 (x64), Build 3.4.0.480
/* Copyright © 2022 ETH Zürich, Educational Development and Technology (LET)
/* 
/* Please visit https://www.github.com/SafeExamBrowser for more information.

# Application started at 2024-05-22 17:58:45.479
# Running on Windows 8.1, Microsoft Windows NT 6.3.9600.0 (x64)
# Computer '1540B-MISHRA' is a  Latitude 3400 manufactured by Dell Inc.
# Runtime-ID: de16fc3e-5d12-401c-b75e-769cd1b07f26

2024-05-22 17:58:45.917 [08] - INFO: Initiating startup procedure...
2024-05-22 17:58:46.370 [08] - INFO: Loading text data...
2024-05-22 17:58:46.370 [08] - DEBUG: [Text] System language is 'en', trying to load data...
2024-05-22 17:58:46.409 [08] - DEBUG: [Text] Data successfully loaded.
2024-05-22 17:58:46.411 [08] - INFO: Starting communication host...
2024-05-22 17:58:46.465 [04] - DEBUG: [RuntimeHost] Communication host is opening...
2024-05-22 17:58:46.507 [04] - DEBUG: [RuntimeHost] Communication host has been opened.
2024-05-22 17:58:46.507 [04] - DEBUG: [RuntimeHost] Successfully started communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/ca319339-ed43-4675-a8ab-79eb260e54ea'.
2024-05-22 17:58:46.507 [08] - INFO: Attempting to verify application integrity...
2024-05-22 17:58:46.977 [08] - INFO: Application integrity successfully verified.
2024-05-22 17:58:46.977 [08] - INFO: Application successfully initialized.

2024-05-22 17:58:47.112 [08] - INFO: ### ------------------------------------ Session Start Procedure ------------------------------------- ###
2024-05-22 17:58:47.114 [08] - INFO: Initializing new session configuration...
2024-05-22 17:58:47.114 [08] - INFO:  -> Client-ID: 12df64d5-9fdb-458f-bed7-a75ab38f9940
2024-05-22 17:58:47.130 [08] - INFO:  -> Runtime-ID: de16fc3e-5d12-401c-b75e-769cd1b07f26
2024-05-22 17:58:47.130 [08] - INFO:  -> Session-ID: f3541d2c-bf48-4f72-b5d1-94e3e7bcadea
2024-05-22 17:58:47.130 [08] - INFO: Initializing application configuration...
2024-05-22 17:58:47.146 [08] - INFO: Found command-line argument for configuration resource: 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852', the URI is valid.
2024-05-22 17:58:47.161 [08] - INFO: [ConfigurationRepository] Attempting to load 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852'...
2024-05-22 17:58:47.192 [08] - DEBUG: [FileResourceLoader] Can't load 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852' as it isn't an existing file.
2024-05-22 17:58:47.208 [08] - DEBUG: [NetworkResourceLoader] Sending HEAD request for 'http://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852'...
2024-05-22 17:58:47.583 [08] - ERROR: [NetworkResourceLoader] Failed to check availability of 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852' via HEAD request!

   Exception Message: An error occurred while sending the request.
   Exception Type: System.Net.Http.HttpRequestException

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.<>c__DisplayClass10_0.<<Execute>b__0>d.MoveNext() in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.Execute(HttpRequestMessage request) in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 107
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.IsAvailable(Uri resource) in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 159

   Inner Exception Message: The request was aborted: Could not create SSL/TLS secure channel.
   Inner Exception Type: System.Net.WebException

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

2024-05-22 17:58:47.599 [08] - DEBUG: [NetworkResourceLoader] HEAD request was not successful, trying GET request for 'http://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852'...
2024-05-22 17:58:47.661 [08] - ERROR: [NetworkResourceLoader] Failed to check availability of 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852' via GET request!

   Exception Message: An error occurred while sending the request.
   Exception Type: System.Net.Http.HttpRequestException

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.<>c__DisplayClass10_0.<<Execute>b__0>d.MoveNext() in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.Execute(HttpRequestMessage request) in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 107
   at SafeExamBrowser.Configuration.DataResources.NetworkResourceLoader.IsAvailable(Uri resource) in C:\Users\appveyor\projects\seb-win-refactoring-6rtltxvrnjx7yhew\SafeExamBrowser.Configuration\DataResources\NetworkResourceLoader.cs:line 176

   Inner Exception Message: The request was aborted: Could not create SSL/TLS secure channel.
   Inner Exception Type: System.Net.WebException

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

2024-05-22 17:58:47.661 [08] - DEBUG: [NetworkResourceLoader] Can't load 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852' since its URI scheme is not supported or the resource is unavailable.
2024-05-22 17:58:47.661 [08] - WARNING: [ConfigurationRepository] No resource loader found for 'seb://stelevate.iac-mygreatlearning.net/api/v1/seb/initial?assessment_id=51373&pb_id=512&user_id=217852'!
2024-05-22 17:58:48.986 [08] - WARNING: The configuration has failed!
2024-05-22 17:58:49.006 [08] - INFO: ### -------------------------------------- Session Start Failed -------------------------------------- ###

2024-05-22 17:58:49.879 [08] - INFO: Initiating shutdown procedure...
2024-05-22 17:58:49.884 [08] - INFO: Stopping communication host...
2024-05-22 17:58:49.892 [08] - DEBUG: [RuntimeHost] Communication host is closing...
2024-05-22 17:58:49.898 [08] - DEBUG: [RuntimeHost] Communication host has been closed.
2024-05-22 17:58:49.901 [08] - DEBUG: [RuntimeHost] Terminated communication host for endpoint 'net.pipe://localhost/safeexambrowser/runtime/ca319339-ed43-4675-a8ab-79eb260e54ea'.
2024-05-22 17:58:49.903 [08] - INFO: Application successfully finalized.

# Application terminated at 2024-05-22 17:58:49.935
