### ISSUE TITLE
Safe exam config issue

### ISSUE THREAD

**Issue by jassica-tbxi** [SafeExamBrowser/seb-win-refactoring#878]
Hi There,

we have safe exam version 3.5.0 and while trying to open it we are getting an error message as shown in the image.

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/165817417/7a21ea5e-eaeb-45e7-ba6c-498d5aeba80c)

This seems like some issue with the configuration. It will be great if you can help us with this on urgent basis.

 - OS: [e.g. Windows 11 Version 23H2]
 - SEB-Version 3.5.0

Attaching the log files for your reference

[2024-05-13_14h29m26s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15298724/2024-05-13_14h29m26s_Runtime.log)
[2024-05-13_14h29m26s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15298725/2024-05-13_14h29m26s_Client.log)

**Comment by dbuechel** [comment]
Thanks for your report. Do you happen to have a (very) big configuration file? The issue seems to be the exchange of the SEB configuration file to be used for the session between the application components of SEB:

```
2024-05-13 14:29:32.319 [01] - ERROR: [RuntimeProxy] Failed to perform 'GetConfiguration'

   Exception Message: The maximum message size quota for incoming messages (65536) has been exceeded. To increase the quota, use the MaxReceivedMessageSize property on the appropriate binding element.
   Exception Type: System.ServiceModel.CommunicationException


Server stack trace: 
   at System.ServiceModel.Channels.ClientDuplexConnectionReader.DecodeMessage(Byte[] buffer, Int32& offset, Int32& size, Boolean& isAtEOF, TimeSpan timeout)
   at System.ServiceModel.Channels.SessionConnectionReader.DecodeMessage(TimeSpan timeout)
   at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout)
   at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout)
   at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, Message& message)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at SafeExamBrowser.Communication.Contracts.ICommunication.Send(Message message)
   at SafeExamBrowser.Communication.Proxies.BaseProxy.Send(Message message) in C:\Users\appveyor\projects\seb-win-refactoring-ist041kp6jai2xxx\SafeExamBrowser.Communication\Proxies\BaseProxy.cs:line 132
   at SafeExamBrowser.Communication.Proxies.RuntimeProxy.GetConfiguration() in C:\Users\appveyor\projects\seb-win-refactoring-ist041kp6jai2xxx\SafeExamBrowser.Communication\Proxies\RuntimeProxy.cs:line 30
```

**Comment by kjehou** [comment]
We have this excact same issue. I have been playing around by adding more url filters and it seems that the issue occurs when the config file is above 133 KB.

In our case, I think we will solve this by replacing our url filters with regular expressions to reduce number of URLFilterRules in the config, but we would really appreciate a fix for this.

Our running version is 3.10.0.826. I am happy to provide more information on this issue @dbuechel.

**Comment by dbuechel** [comment]
Please provide the configuration files which reproduce the issue.

**Comment by dbuechel** [comment]
The maximum message size has been at 65 KB and I have increased it now to 1 MB, which should in the most of all cases be more than sufficient. Please retest your use case with the latest development build of version 3.11.0: https://sebdev.ethz.ch/api/buildjobs/s0h7broksqt5hp7y/artifacts/SEB_3.11.0.885_SetupBundle.exe.

**Comment by kjehou** [comment]
Thank you very much @dbuechel <3 I have tested the new build 3.11.0.885 and SEB starts as normal (with the oversized config), which can only mean that the issue has been fixed in that release :)
